### ISSUE TITLE
MELPA?

### ISSUE THREAD

**Issue by alphapapa** [riscy/shx-for-emacs#1]
Hi there,

Somehow I just stumbled across this package.  This is very cool!  Are you planning to submit it to MELPA?

**Comment by riscy** [comment]
Thank you!  I'm in the process of getting it up to snuff for MELPA -- should be this weekend that I get that PR up.  I'll let you know when it's there. :)

**Comment by riscy** [comment]
https://github.com/melpa/melpa/pull/4749

**Comment by riscy** [comment]
It's up!
