### ISSUE TITLE
feature request for :e -- understand tramp

### ISSUE THREAD

**Issue by neeasade** [riscy/shx-for-emacs#13]
it would be nice if `:e` when used in a tramp shell using an absolute path used the remote completion and file -- ie `:e /etc/environment` should be the remote file, not the local one.

**Comment by riscy** [comment]
This is definitely worth looking at, thanks.  I think even `ls /etc/enviro`<kbd>tab</kbd> should use the remote host for completion, but it looks like it doesn't.

**Comment by riscy** [comment]
I think this is fixed now in 1.1.2 -- there was an extra comint variable I didn't know I had to set.  Let me know if it works out for you. :)

**Comment by riscy** [comment]
Closing for now since I believe this is fixed!
