### ISSUE TITLE
Fix gnuplot commands under Windows build of Emacs

### ISSUE THREAD

**Issue by p3r7** [riscy/shx-for-emacs#17]
Plotting shell commands can work under the Windows build of Emacs.

One requirement of course is to have gnuplot installed (either through MSYS or Cygwin, both got tested).

There is just a small specificity that would need to be changed to make shx compatible with this setup.

It has to do with quoting inside [shx-insert-plot](https://github.com/riscy/shx-for-emacs/blob/master/shx.el#L542):

This line:

```el
plot-command " \"" (shell-quote-argument filename) "\" "
```

Would have to be conditionally replaced with:

```el
plot-command " " (shell-quote-argument filename) " "
```

This might have to do with the way `shell-quote-argument` behaves under windows:

```el
(shell-quote-argument "aa")             ; => "\"aa\""
```

I've also attempted to play around with the value of `w32-quote-process-args` but did not end up with anything that works.

**Comment by riscy** [comment]
Interesting.  Let me confirm whether the `\"` are even necessary in unixlike environments -- maybe they can be dropped entirely!

**Comment by riscy** [comment]
Double-checked and the `\"` are indeed necessary in unixlike environments.   I think it's not too big of a hassle to add windows detection for these -- stay tuned.

**Comment by riscy** [comment]
I figure any unescaped `"` at the start or beginning of the string can safely be removed, so the fix turned out to be relatively simple -- I don't have a Windows PC to test on, but maybe this works for you?

**Comment by p3r7** [comment]
I'll test it during the day. Thanks!

**Comment by p3r7** [comment]
Tested under windows with filenames with and without spaces.

Both situations work.
