### ISSUE TITLE
History commands for shx in a new session

### ISSUE THREAD

**Issue by tddsg** [riscy/shx-for-emacs#2]
Hi,

When opening a new shell session, it seems that `shx` never recalls the history of command lines entered before by pressing "Ctrl" and up, down arrow keys. The only command that I can get is `:eval (shx-wordwrap 90)`

Hence, I'd like to ask if `shx` supports such feature?

Thanks!

**Comment by riscy** [comment]
It looks like you've found a bug.  I'll fix this in the next release.  Thank you. :)

If you want a quick fix, removing the line `shx--restore-kept-commands` from the `shx--activate` function should sort things out.

**Comment by tddsg** [comment]
Thanks for the suggestion! It works like a charm now! :+1:

**Comment by riscy** [comment]
All patched up in the latest release.  Thanks again!
