### ISSUE TITLE
Directory tracking over remote connection

### ISSUE THREAD

**Issue by Blade6570** [riscy/shx-for-emacs#26]
If I am over ssh connection then `:e <filename>` is searching for the filename in the `\tmp` directory instead of the current directory. Is this a bug in my setup or is it desired?  

I am on Emacs-27, Ubuntu 20.04. Installed the shx from Melpa and called it by `M-x shx`

**Comment by riscy** [comment]
Hi! Are you using `:ssh` (<kbd>:help ssh</kbd>) or `ssh` to connect to the host?

If you're using `:ssh`, shx should track your directory (and <kbd>M-return</kbd> should run `shell-resync-dirs` to resync you).  (Unless they're a bug, and then we should dig deeper -- although I was just able to confirm this is working for me.)

If you're using `ssh` on its own, then shx won't be able to track the remote directory, and `:e xyz` won't work.

**Comment by Blade6570** [comment]
Okay, I see the problem now. It works if I do `:ssh` but not if I open `shx` from a remote file with `M-x`.

Thanks
