### ISSUE TITLE
Empty prompts if window config changes

### ISSUE THREAD

**Issue by WhatDothLife** [riscy/shx-for-emacs#27]
I'm sorry to post this issue here, but I'm desperately searching for advice. 
I noticed that when I'm using zsh for shell-mode, each time the 
window configuration changes, an empty prompt is spawned. 
So leaving it opened in the background for some time results in a cluttered shell-buffer.
Strangely, this is not the case for bash. 

I thought this is a good place to get help, since it gathers most shell-mode hackers.
I'm thankful for any advice. Feel free to close this immediately. Anyways, dank package!

**Comment by riscy** [comment]
Just spitballing, but do you know what the contents of `window-configuration-change-hook` is when this happens?

**Comment by WhatDothLife** [comment]
The value is `(evil--jumps-window-configuration-hook t)`. It might be an evil issue though. Anyways, I noticed that this does not happen when using good ol' bash, so I'm fine with using bash at the moment. Interestingly, it also happens for fish shell...
