### ISSUE TITLE
shx-mode in eshell

### ISSUE THREAD

**Issue by nayefc** [riscy/shx-for-emacs#3]
Is there anyway to use shx-mode with `eshell`? When I run shx-mode in `shell`, I get this when I hit return which makes it unusable:
`shx-point-on-input-p: Wrong type argument: processp, nil`

**Comment by riscy** [comment]
Unfortunately there isn't -- shx hooks `comint-mode`'s input/output handling.  Many REPLs and regular old `shell` use `comint-mode`, but `eshell` doesn't.

You can check if a buffer's major mode derives from `comint-mode` by running
```
M-: (derived-mode-p 'comint-mode)
```
But I should probably add a descriptive warning when you try to enable shx in a non-comint-mode buffer.  Thanks for bringing this to my attention!

**Comment by riscy** [comment]
Thanks for this.  Sorry shx doesn't work in eshell -- looks like that would be a big project.
